name: End-to-end tests

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: npm install
        working-directory: ../.
      - name: Start Application
        run: node app.js
        working-directory: ../.
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
